### ISSUE TITLE
.dns Extension

### ISSUE THREAD

**Issue by britesc** [compilenix/vscode-zonefile#3]
Hi,
Could you please add .dns as a default extension.
.dns is used by the DNS Server on Windows.
Thank you.
jB

**Comment by compilenix** [comment]
Sure.
When i have time, maybe next weekend or so.

**Comment by compilenix** [comment]
Done, version 0.0.4 (97ed6aaa06e0f57ab74783605224a37ad7378390)

**Comment by britesc** [comment]
Thank you and kind regards,

Julian
